### ISSUE TITLE
Can't run main.py on pycharm

### ISSUE THREAD

**Issue by HectorJD** [niavlys/memoryKivy#5]
I'm new on kivy so I'm just looking at some open code and this game seems to be great but, when I try to run it, I get the following errors. 
![capture](https://cloud.githubusercontent.com/assets/26104453/23446129/9b17b156-fe0e-11e6-9299-5dd69c49b895.JPG)
Would you tell me what is wrong?

**Comment by niavlys** [comment]
well, it [looks like ](https://docs.python.org/3.0/whatsnew/3.0.html#builtins)has_key has been removed from python3 buildin dict's function.
